version: '3.8'

services:
  mtogo.auth:
    image: mtogo.auth
    build:
      context: .
      dockerfile: src/Auth.Web/Dockerfile
    ports:
      - "8083:80"
    networks:
      - kafka

networks:
  kafka:
    external: true
